version: '3.9'
services:
  db:
    image: postgres:14.1-alpine

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres

    ports:
      - '5432:5432'
  
  api:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db